# Uji Coba Prediksi

## Importing Libraries

In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder

import joblib

## Importing Model

In [37]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [38]:
model = joblib.load('/content/drive/MyDrive/PYTHON/IDCamp Data Science Expert/random_forest_model.pkl')

## Data Test Preparation

In [39]:
sample_data = {
    "EmployeeId": 1,
    "Age": 35,
    "BusinessTravel": "Travel_Rarely",
    "DailyRate": 1100,
    "Department": "Research & Development",
    "DistanceFromHome": 5,
    "Education": 3,
    "EducationField": "Life Sciences",
    "EmployeeCount": 1,
    "EnvironmentSatisfaction": 4,
    "Gender": "Male",
    "HourlyRate": 70,
    "JobInvolvement": 3,
    "JobLevel": 2,
    "JobRole": "Research Scientist",
    "JobSatisfaction": 3,
    "MaritalStatus": "Married",
    "MonthlyIncome": 6000,
    "MonthlyRate": 20000,
    "NumCompaniesWorked": 2,
    "Over18": "Y",
    "OverTime": "No",
    "PercentSalaryHike": 15,
    "PerformanceRating": 3,
    "RelationshipSatisfaction": 2,
    "StandardHours": 80,
    "StockOptionLevel": 1,
    "TotalWorkingYears": 10,
    "TrainingTimesLastYear": 3,
    "WorkLifeBalance": 3,
    "YearsAtCompany": 6,
    "YearsInCurrentRole": 4,
    "YearsSinceLastPromotion": 1,
    "YearsWithCurrManager": 3
}

In [40]:
sample_df = pd.DataFrame([sample_data])
sample_df

,EmployeeId,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1,35,Travel_Rarely,1100,Research & Development,5,3,Life Sciences,1,4,...,2,80,1,10,3,3,6,4,1,3

### Data Summary

In [41]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeId                1 non-null      int64
 1   Age                       1 non-null      int64
 2   BusinessTravel            1 non-null      object
 3   DailyRate                 1 non-null      int64
 4   Department                1 non-null      object
 5   DistanceFromHome          1 non-null      int64
 6   Education                 1 non-null      int64
 7   EducationField            1 non-null      object
 8   EmployeeCount             1 non-null      int64
 9   EnvironmentSatisfaction   1 non-null      int64
 10  Gender                    1 non-null      object
 11  HourlyRate                1 non-null      int64
 12  JobInvolvement            1 non-null      int64
 13  JobLevel                  1 non-null      int64
 14  JobRole                   1 non-null      object
 15  JobSatisfaction           1 non-null      int64
 16  MaritalStatus             1 non-null      object
 17  MonthlyIncome             1 non-null      int64
 18  MonthlyRate               1 non-null      int64
 19  NumCompaniesWorked        1 non-null      int64
 20  Over18                    1 non-null      object
 21  OverTime                  1 non-null      object
 22  PercentSalaryHike         1 non-null      int64
 23  PerformanceRating         1 non-null      int64
 24  RelationshipSatisfaction  1 non-null      int64
 25  StandardHours             1 non-null      int64
 26  StockOptionLevel          1 non-null      int64
 27  TotalWorkingYears         1 non-null      int64
 28  TrainingTimesLastYear     1 non-null      int64
 29  WorkLifeBalance           1 non-null      int64
 30  YearsAtCompany            1 non-null      int64
 31  YearsInCurrentRole        1 non-null      int64
 32  YearsSinceLastPromotion   1 non-null      int64
 33  YearsWithCurrManager      1 non-null      int64
dtypes: int64(26), object(8)
memory usage: 404.0+ bytes

### Dropping Unused Features

In [42]:
sample_test_df = sample_df.drop(['BusinessTravel', 'Education', 'OverTime'], axis=1)
sample_test_df

,EmployeeId,Age,DailyRate,Department,DistanceFromHome,EducationField,EmployeeCount,EnvironmentSatisfaction,Gender,HourlyRate,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1,35,1100,Research & Development,5,Life Sciences,1,4,Male,70,...,2,80,1,10,3,3,6,4,1,3

### Labelling Data

In [43]:
sample_test_df['Department'] = preprocessing.LabelEncoder().fit_transform(sample_test_df['Department'])
sample_test_df['EducationField'] = preprocessing.LabelEncoder().fit_transform(sample_test_df['EducationField'])
sample_test_df['Gender'] = preprocessing.LabelEncoder().fit_transform(sample_test_df['Gender'])
sample_test_df['JobRole'] = preprocessing.LabelEncoder().fit_transform(sample_test_df['JobRole'])
sample_test_df['MaritalStatus'] = preprocessing.LabelEncoder().fit_transform(sample_test_df['MaritalStatus'])
sample_test_df['Over18'] = preprocessing.LabelEncoder().fit_transform(sample_test_df['Over18'])

### Standarization

In [44]:
Scaler = StandardScaler()
sample_test_df = Scaler.fit_transform(sample_test_df)

### Testing Model

In [45]:
prediction = model.predict(sample_test_df)
print(f"Prediction: {prediction}")

Prediction: [0]

In [46]:
sample_df['Attrition_Pred'] = prediction
sample_df['Attrition_Pred'] = sample_df['Attrition_Pred'].apply(lambda x: 'False' if x == 0 else 'True')
sample_df

,EmployeeId,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EnvironmentSatisfaction,...,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition_Pred
0,1,35,Travel_Rarely,1100,Research & Development,5,3,Life Sciences,1,4,...,80,1,10,3,3,6,4,1,3,False